version: '3.3'
services:
 eureka:
  build: ./eureka
  ports:
   - "8761:8761"
  expose:
   - "8761"
 microservicio:
  build: ./microservicio
  ports:
   - "3333:3333"
  expose:
   - "3333"
  depends_on:
   - eureka
  links:
   - eureka
 zuul:
  build: ./zuul
  ports:
   - "9000:9000"
  expose:
   - "9000"
  depends_on:
   - eureka
   - microservicio
  links:
   - eureka
   - microservicio